### ISSUE TITLE
error

### ISSUE THREAD

**Issue by xenfovn** [IsEmil/ironbrew-bot#1]
getting this error after upload file
![image](https://user-images.githubusercontent.com/55439243/160973520-04c4c3e9-3e27-4b70-ad4a-65fc66eb85e5.png)

**Comment by 023948799e213e21b53eb83785356208** [comment]
You need .net 2.0 for ironbrew2 to run

**Comment by IsEmil** [comment]
Hey! Please make sure to have these versions installed.

[.NET 6.0](https://dotnet.microsoft.com/en-us/download/dotnet/6.0)
[.NET Core 3.1](https://dotnet.microsoft.com/en-us/download/dotnet/3.1)
[.NET Core 2.0](https://dotnet.microsoft.com/en-us/download/dotnet/2.0)

**Comment by IsEmil** [comment]
I will also make sure to redo the README to make it easier to understand for anyone else trying to use this Ironbrew bot.

**Comment by xenfovn** [comment]
> I will also make sure to redo the README to make it easier to understand for anyone else trying to use this Ironbrew bot.

can u make bot for this source ? moonsec https://github.com/RealSourceLeaks/moonsec-source-code
