### ISSUE TITLE
 An error occurred executing Command: obfuscate. Please try again later. #1 

### ISSUE THREAD

**Issue by ghost** [IsEmil/ironbrew-bot#13]

**Comment by IsEmil** [comment]
Could you show the error?

**Comment by SmoxHub** [comment]
It's not in VS code it's the bot sending it 
Execution Error
An error occurred executing Command: obfuscate. Please try again later.
Today at 2:45 PM

**Comment by IsEmil** [comment]
Hmm I'll look into the issue when I get time.
